#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.23.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([ 4.80924144e-310,  0.00000000e+000,  0.00000000e+000,
        0.00000000e+000,  0.00000000e+000,  1.57111455e-076,
        3.21442856e-057,  6.80918640e-091,  3.50758465e-033,
       -3.66841750e+178])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
np.empty(10).size * np.empty(10).itemsize
np.empty(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a=np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr=np.arange(6)
print(arr)
rev=np.flip(arr)
print(rev)

[0 1 2 3 4 5]
[5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
n = np.arange(0,9).reshape(3,3)
n

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
n = np.random.randint(0,101,27).reshape(3,3,3)
n

array([[[ 0, 21, 73],
        [82, 80, 17],
        [ 2, 39,  5]],

       [[65, 42, 28],
        [55, 58, 35],
        [ 9,  2, 36]],

       [[35, 38, 98],
        [12, 22, 60],
        [48, 39, 47]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
n = np.random.randint(0,101,100).reshape(10,10)
print(n)

print("Minimum value: ",np.min(n))
print("Maximum value: ",np.max(n))

[[ 37   7  90  66  12  86  21  41  52  66]
 [  1  85   5  91  89  22  74  44  89  10]
 [ 83  51  38  30  29  17  42  96  38  19]
 [ 63  33  89  38  81  88   8   1  73  20]
 [ 65  46  21  53  16  18  39  74  52  59]
 [  4  91  92  78  16   2   3  12  95  32]
 [ 56  11  49  25  46  30   0  76   0  69]
 [ 27  43  13  85  15  25  65  96  97  83]
 [  7  11  44  88  73  61  14  93  76 100]
 [ 93  46  98  49  52  53  39  83  16  36]]
Minimum value:  0
Maximum value:  100


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
v = np.random.randint(0,31,30)
v

array([15,  6, 15, 24, 18, 17,  1,  0, 21, 26,  2, 11, 18,  1,  8, 21,  6,
        9,  2,  8, 22,  8, 15, 24, 28,  3,  4,  7,  2, 10])

In [ ]:
mean_v = np.mean(v)
mean_v

11.733333333333333

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((5,5))
a = np.pad(a,2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
True

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
n = np.zeros((5,5))
np.fill_diagonal(n[1:],[1,2,3,4])
print(n)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
n = np.zeros((8,8))
n[1::2,::2] = 1
n[::2,1::2] = 1
print(n)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
n = np.array([[0, 1], [1, 0]])
n_8x8 = np.tile(n,(4,4))
n_8x8

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
n = np.random.normal(1.0,2.0,25)
n

array([ 3.43671827,  1.70773138,  1.53393919,  3.1483584 ,  2.07141695,
        2.79696781, -0.65361733,  0.21465788,  1.89917658,  2.88376176,
        2.18904774,  4.11663273,  0.87671196, -1.51504518,  2.75134443,
        2.42132789, -0.30792686,  0.09895681,  0.69789325,  0.15464459,
        2.35834324, -0.45421439,  2.57933556,  0.8654012 , -0.47617234])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
rgba_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

color = np.array((255, 0, 0, 128), dtype=rgba_dtype)

red = color['R']
green = color['G']
blue = color['B']
alpha = color['A']

print(f"RGBA Color: ({red}, {green}, {blue}, {alpha})")


RGBA Color: (255, 0, 0, 128)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
matrix2 = np.array([[1,2],[3,4],[5,6]])

print(np.dot(matrix1,matrix2))

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr = np.arange(1,9)

arr[(arr>3)&(arr<8)] *= -1

print(arr)

[ 1  2  3 -4 -5 -6 -7  8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan
0
array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
arr = np.array([1.4,2.5,3.6,4.1])
round = np.floor(arr)
print(round)

[1. 2. 3. 4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
arr1 = np.array([3, 4, 5, 6, 7])
arr2 = np.array([1, 2, 3, 4, 5])
common =np.intersect1d(arr1,arr2)
print(common)

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#GOOGLED
np.warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
True

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
#GOOGLED
from datetime import datetime, timedelta

today = datetime.now().date()
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2023-09-26
Today: 2023-09-27
Tomorrow: 2023-09-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
#GOOGLED
start_date = np.datetime64('2016-07-01')
end_date = np.datetime64('2016-08-01')

dates_in_july_2016 = np.arange(start_date, end_date, dtype='datetime64[D]')

print(dates_in_july_2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

A += B
A *= (-A / 2)

print(A)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
rand = np.random.randint(0,101,100)
print(rand)

meth1 = np.floor(rand)
print(meth1)

meth2 = np.trunc(rand)
print(meth2)

meth3 = rand.astype(int)
print(meth3)

meth4 = np.rint(rand).astype(int)
print(meth4)

[ 84  61  83  56  73  35  46  92  32  82  95  46   1  84  90  11  97  74
   2  12  43  37  52 100  43  49  64  33  40  82  76  12  49   1  17  49
  42  91  58  60  50 100  72   1  82  72  39   0  93   5  35  33  70  52
  50  40  63  54  86  10  39   7  29  43   5  74   6  19   8  99  87  34
  74   6  61   0  21  35  82  44  50  84  28  95  78  13  21  58  19   1
  90   4  24  88  77  29  76  99  85  40]
[ 84.  61.  83.  56.  73.  35.  46.  92.  32.  82.  95.  46.   1.  84.
  90.  11.  97.  74.   2.  12.  43.  37.  52. 100.  43.  49.  64.  33.
  40.  82.  76.  12.  49.   1.  17.  49.  42.  91.  58.  60.  50. 100.
  72.   1.  82.  72.  39.   0.  93.   5.  35.  33.  70.  52.  50.  40.
  63.  54.  86.  10.  39.   7.  29.  43.   5.  74.   6.  19.   8.  99.
  87.  34.  74.   6.  61.   0.  21.  35.  82.  44.  50.  84.  28.  95.
  78.  13.  21.  58.  19.   1.  90.   4.  24.  88.  77.  29.  76.  99.
  85.  40.]
[ 84.  61.  83.  56.  73.  35.  46.  92.  32.  82.  95.  46.   1.  84.
  90.  11.  9

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
np.tile?

In [ ]:
matrix = np.tile(np.arange(5),(5,1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
v = np.arange(1, 11) / 11
v

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
v = np.random.randint(1,11,10)
sorted = np.sort(v)
print(sorted)

[1 1 3 3 4 4 7 7 7 8]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
total = sum(arr)
print(total)

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,11,10)
B = np.random.randint(0,11,10)

equal = np.array_equal(A,B)

if equal:
  print("Equal")
else:
  print("Not equal")

Equal


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
#GOOGLED
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

arr.flags.writeable = False

if arr.flags.writeable:
    print("The array is mutable.")
else:
    print("The array is read-only.")

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
#GOOGLED
cartesian = np.random.randint(1,21,20).reshape(10,2)

x = cartesian[:, 0]
y = cartesian[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)

polar = np.column_stack((r,theta))

print(cartesian)
print(polar)

[[12 16]
 [ 3  6]
 [18 16]
 [10 13]
 [ 2 15]
 [ 6 19]
 [19 13]
 [13  4]
 [13  2]
 [ 7  4]]
[[20.          0.92729522]
 [ 6.70820393  1.10714872]
 [24.08318916  0.72664234]
 [16.40121947  0.9151007 ]
 [15.13274595  1.43824479]
 [19.92485885  1.26491746]
 [23.02172887  0.60005021]
 [13.60147051  0.29849893]
 [13.15294644  0.15264933]
 [ 8.06225775  0.51914611]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
np.argmax?

In [ ]:
v = np.random.randint(0,20,10)
print(v)
max = np.argmax(v)
v[max] = 0
print(v)

[ 5  5 18 14  6 19  5 11 15  9]
[ 5  5 18 14  6  0  5 11 15  9]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

n = len(X)
m = len(Y)
C = np.empty((n, m))

for i in range(n):
    for j in range(m):
        C[i, j] = 1.0 / (X[i] - Y[j])

print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
arr = np.array([1,2,3,4,5])

for i in arr:
  print(i)

1
2
3
4
5


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
#GOOGLED
vector = np.array([1, 3, 5, 7, 9, 11])

target_scalar = 6

closest_index = np.abs(vector - target_scalar).argmin()

closest_value = vector[closest_index]

print("Closest Value:", closest_value)

Closest Value: 5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [6]:
dtype = [('x', int), ('y', int), ('r', int), ('g', int), ('b', int)]

structured_array = np.empty(1, dtype=dtype)

structured_array['x'] = 10
structured_array['y'] = 20
structured_array['r'] = 255
structured_array['g'] = 0
structured_array['b'] = 0

print(structured_array)

[(10, 20, 255, 0, 0)]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [10]:
coordinates = np.random.randint(0,101,200).reshape(100,2)

n = coordinates.shape[0]
distances = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        diff = coordinates[i] - coordinates[j]
        distances[i, j] = np.sqrt(np.dot(diff, diff))

print(distances[0, 1])

74.30343195303969


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [12]:
float_array = np.array([3.14, 2.71, 1.618], dtype=np.float32)
int_array = np.empty_like(float_array, dtype=np.int32)
np.copyto(int_array, float_array.view(np.int32))
print(int_array)

[1078523331 1076719780 1070537376]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [13]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
for index, value in np.ndenumerate(arr):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [17]:
shape = (5, 5)
p = 10

array = np.zeros(shape, dtype=int)

indices = np.random.choice(np.arange(shape[0] * shape[1]), p, replace=False)

array.flat[indices] = 1

print(array)

[[0 1 1 0 0]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 1 0 1 1]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [18]:
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(matrix)

row_mean = np.mean(matrix,axis=1)

centered = matrix - row_mean[np.newaxis]
print(centered)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1. -3. -5.]
 [ 2.  0. -2.]
 [ 5.  3.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [20]:
matrix = np.array([[5, 2, 8],[3, 9, 1],[7, 4, 6]])
n = 1
sorted_indices = np.argsort(arr[:, n])
sorted_arr = arr[sorted_indices]
print(sorted_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [22]:
arr = np.array([[1, 0, 0],[0, 0, 0],[4, 0, 0],[0, 2, 0]])
null_columns = np.all(arr == 0, axis=0)
if np.any(null_columns):
    print("The array has null columns.")
else:
    print("The array does not have null columns.")

The array has null columns.


#### 61. Find the nearest value from a given value in an array (★★☆)

In [24]:
arr = np.array([2.5, 1.0, 4.8, 3.2, 7.1])
target_value = int(input("Enter a value: "))
differences = np.abs(arr - target_value)
nearest_index = differences.argmin()
nearest_value = arr[nearest_index]
print("Nearest Value:", nearest_value)
print("Index of Nearest Value:", nearest_index)

Enter a value: 5
Nearest Value: 4.8
Index of Nearest Value: 2



#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [27]:
#GOOGLED
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4],
                   [5],
                   [6]])

iterator1 = np.nditer(array1)
iterator2 = np.nditer(array2)

total_sum = 0

for val1, val2 in zip(iterator1, iterator2):
    total_sum += val1 + val2

print("Sum of the two arrays:", total_sum)

Sum of the two arrays: 21


#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
original_vector = np.array([1, 2, 3, 4, 5])
indices_to_increment = np.array([1, 3, 3, 4])

mask = np.zeros_like(original_vector)
mask_indices = np.unique(indices_to_increment)
mask[mask_indices] = 1

result_vector = original_vector + mask

print("Original Vector:", original_vector)
print("Indices to Increment:", indices_to_increment)
print("Result Vector:", result_vector)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [28]:
X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 2, 1, 4, 2])
N = len(I)
F = np.zeros(N, dtype=X.dtype)

for i in range(N):
    F[i] += X[I[i]]

print("Vector X:", X)
print("Index list I:", I)
print("Accumulated Array F:", F)

Vector X: [1 2 3 4 5]
Index list I: [0 2 1 4 2]
Accumulated Array F: [1 3 2 5 3]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [30]:
image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)

reshaped_image = image.reshape(-1, 3)

unique_colors = np.unique(reshaped_image, axis=0)

num_unique_colors = unique_colors.shape[0]

print("Number of Unique Colors:", num_unique_colors)

Number of Unique Colors: 100


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [33]:
#GOOGLED
array_4d = np.random.rand(2, 3, 4, 5)

sum_last_two_axes = np.sum(array_4d, axis=(2, 3))

print("Original 4D Array Shape:", array_4d.shape)
print("Sum over Last Two Axes Shape:", sum_last_two_axes.shape)
print("Sum over Last Two Axes:")
print(sum_last_two_axes)


Original 4D Array Shape: (2, 3, 4, 5)
Sum over Last Two Axes Shape: (2, 3)
Sum over Last Two Axes:
[[11.23292539  9.2599692   8.33569806]
 [11.06333672 11.54335769 11.12848967]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [34]:
D = np.array([1, 2, 3, 4, 5, 6])

S = np.array([0, 1, 0, 1, 2, 2])

unique_indices = np.unique(S)
subset_means = np.zeros(len(unique_indices))

for i, index in enumerate(unique_indices):
    subset = D[S == index]
    subset_mean = np.mean(subset)
    subset_means[i] = subset_mean

print("Vector D:", D)
print("Vector S:", S)
print("Subset Means:", subset_means)

Vector D: [1 2 3 4 5 6]
Vector S: [0 1 0 1 2 2]
Subset Means: [2.  3.  5.5]


#### 69. How to get the diagonal of a dot product? (★★★)

In [35]:
A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
B = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])

dot_product = np.dot(A, B)
diagonal = np.einsum('ii->i', dot_product)

print("Diagonal of Dot Product:")
print(diagonal)

Diagonal of Dot Product:
[30 69 90]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [36]:
original_vector = np.array([1, 2, 3, 4, 5])
num_zeros = 3

new_vector = np.zeros(len(original_vector) + (len(original_vector) - 1) * num_zeros, dtype=original_vector.dtype)
new_vector[::num_zeros + 1] = original_vector

print("Original Vector:", original_vector)
print("New Vector with Consecutive Zeros:", new_vector)

Original Vector: [1 2 3 4 5]
New Vector with Consecutive Zeros: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [38]:
array1 = np.random.rand(5, 5, 3)
array2 = np.random.rand(5, 5)
result = array1 * array2[:, :, np.newaxis]

print("Array1 Shape:", array1.shape)
print("Array2 Shape:", array2.shape)
print("Result:", result.shape)

Array1 Shape: (5, 5, 3)
Array2 Shape: (5, 5)
Result: (5, 5, 3)


#### 72. How to swap two rows of an array? (★★★)

In [41]:
array = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

row1_index = 1
row2_index = 2
array[[row1_index, row2_index]] = array[[row2_index, row1_index]]

print(array)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.array([0, 2, 2, 0, 1, 0, 0, 1])

max_value = len(C) - 1

A = np.repeat(np.arange(max_value + 1), C)

print("Generated Array A:")
print(A)

print("np.bincount(A):", np.bincount(A))
print("C:", C)
print("Are np.bincount(A) and C equal?", np.array_equal(np.bincount(A), C))

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [42]:
#GOOGLED
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

window_size = 3

averages = []

for i in range(len(arr) - window_size + 1):
    window = arr[i:i+window_size]
    average = np.mean(window)
    averages.append(average)

print("Averages:", averages)

Averages: [2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [3]:
Z = np.array([1, 2, 3, 4, 5, 6])

num_columns = 3

num_rows = len(Z) - num_columns + 1

result_array = np.zeros((num_rows, num_columns), dtype=int)

for i in range(num_rows):
    result_array[i] = Z[i:i+num_columns]

print(result_array)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [4]:
my_bool_array = np.array([True, False, True])

my_bool_array = ~my_bool_array

print(my_bool_array)

my_float_array = np.array([1.0, 2.0, 3.0])

my_float_array = -my_float_array

print(my_float_array)

[False  True False]
[-1. -2. -3.]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)